name: enjoy_diving
description: A flutter application about diving spots.
version: 0.0.3+05082214

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^0.9.0
  package_info: ^0.4.0+16

  cached_network_image: ^2.0.0
  location: ^2.5.4
  queries: ^0.1.12
  vector_math: any
  scoped_model: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  android: true
  ios: false
  image_path: assets/launcher/ic_launcher.png
  adaptive_icon_background: assets/launcher/sea_background.png
  adaptive_icon_foreground: assets/launcher/ic_launcher.png

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/spots.json
    - assets/launcher/ic_launcher.png
    - assets/tampon_48x18.png

  fonts:
    - family: KaushanScript
      fonts:
      - asset: assets/fonts/KaushanScript-Regular.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
